### ISSUE TITLE
Missing androidfs/{proc, sys, dev} folders

### ISSUE THREAD

**Issue by GerardGarcia** [sestus/acestream-openelec#1]
To make it work on a Raspberry PI 2 running Libreelec 8.0.1 I had to create these folders. Probably they were not commited because they are empty.

Thanks for taking the time to make acestream work again!

**Comment by sestus** [comment]
Good catch @GerardGarcia . Indeed, these directories were empty, thus not committed. I 've fixed that now, thanks for pointing it out!
